from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone

from tools.models import ComplianceViolation, ReportSummary
from tools.report_badges import framework_badge, metric_badge, priority_badge, severity_badge, status_badge


def render_report_markdown(
    *,
    target_path: str,
    violations: list[ComplianceViolation],
    summary: ReportSummary,
    scanners: list[str],
) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    scanner_line = " · ".join(scanners) if scanners else "mask_pii · audit_secrets · scan_infrastructure"

    lines = [
        "# Security Audit Report",
        "",
        "**Agentic K-SecOps** · Compliance Self-Assessment (101통제 Lab Format)",
        "",
        "| | |",
        "|---|---|",
        f"| **Target** | `{target_path}` |",
        f"| **Generated** | {generated_at} |",
        f"| **Scanners** | {scanner_line} |",
        "| **Auditor** | Agentic K-SecOps MCP Pipeline |",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| {metric_badge('Critical', summary.critical, 'D32F2F')} | **{summary.critical}** |",
        f"| {metric_badge('High', summary.high, 'F57C00')} | **{summary.high}** |",
        f"| {metric_badge('미흡_통제', summary.non_compliant_controls, 'D32F2F')} | **{summary.non_compliant_controls}** controls |",
        f"| {metric_badge('즉시_조치', summary.immediate_actions, 'D32F2F')} | **{summary.immediate_actions}** actions |",
        "",
        f"> 배포 전 검증 결과, **즉시 조치 {summary.immediate_actions}건**이 확인되었습니다.",
        "",
        "---",
        "",
        "## Compliance Overview",
        "",
        _render_overview_table(violations),
        "",
        "---",
        "",
        "## Findings Detail",
        "",
        "101통제 셀프진단 Lab 형식: **진단 질문 → 결함 사유 → 권고 조치 → 필요 증적**",
        "",
    ]

    for violation in violations:
        lines.extend(_render_violation_section(violation))
        lines.append("---")
        lines.append("")

    lines.extend(_render_action_sections(violations))
    lines.extend(
        [
            "---",
            "",
            "*Report generated by Agentic K-SecOps. Deficiency reasons and recommended actions "
            "are sourced verbatim from `src/compliance/finding_rules.json`.*",
            "",
        ]
    )
    return "\n".join(lines)


def _render_overview_table(violations: list[ComplianceViolation]) -> str:
    if not violations:
        return "_No compliance violations mapped._"

    rows = ["| Status | Control | Framework | Category |", "|--------|---------|-----------|----------|"]
    seen: set[str] = set()
    for violation in violations:
        if violation.control_id in seen:
            continue
        seen.add(violation.control_id)
        rows.append(
            "| "
            + " | ".join(
                [
                    status_badge(violation.compliance_status),
                    f"{violation.control_id} {violation.control_title}",
                    framework_badge(violation.framework),
                    violation.category,
                ]
            )
            + " |"
        )
    return "\n".join(rows)


def _render_violation_section(violation: ComplianceViolation) -> list[str]:
    title = violation.deficiency_reason.split("—")[0].strip()
    return [
        f"### {violation.violation_id} · {title}",
        "",
        "| Field | Detail |",
        "|-------|--------|",
        f"| Severity | {severity_badge(violation.severity)} |",
        f"| Resource | `{violation.resource}` |",
        f"| Scanner | `{violation.scanner}` |",
        f"| Framework | {framework_badge(violation.framework)} **{violation.control_id}** |",
        f"| Status | {status_badge(violation.compliance_status)} |",
        f"| Priority | {priority_badge(violation.action_priority)} |",
        "",
        "**진단 질문 (Lab)**  ",
        violation.checklist_question,
        "",
        "**결함 사유**  ",
        violation.deficiency_reason,
        "",
        "**결함 상세**  ",
        violation.deficiency_detail,
        "",
        "**권고 조치**  ",
        violation.recommended_action,
        "",
        "**필요 증적**  ",
        violation.evidence_required,
        "",
    ]


def _render_action_sections(violations: list[ComplianceViolation]) -> list[str]:
    lines = ["## Recommended Actions", ""]
    for title, priority in [("Immediate", "즉시"), ("Short-term", "단기")]:
        items = [v for v in violations if v.action_priority == priority]
        lines.append(f"### {title}")
        lines.append("")
        if not items:
            lines.append("_None._")
            lines.append("")
            continue
        lines.extend(["| # | Action | Control | Tool |", "|---|--------|---------|------|"])
        for index, violation in enumerate(items, start=1):
            action = violation.recommended_action.split(",")[0]
            lines.append(
                f"| {index} | {action} | {violation.control_id} | `{violation.tool_reference}` |"
            )
        lines.append("")
    return lines


def summarize_report(violations: list[ComplianceViolation], scan_summary: dict | None = None) -> ReportSummary:
    if scan_summary:
        critical = scan_summary.get("critical", 0)
        high = scan_summary.get("high", 0)
    else:
        counts = Counter(v.severity for v in violations)
        critical = counts.get("CRITICAL", 0)
        high = counts.get("HIGH", 0)

    control_ids = {v.control_id for v in violations}
    immediate = sum(1 for v in violations if v.action_priority == "즉시")

    return ReportSummary(
        critical=critical,
        high=high,
        non_compliant_controls=len(control_ids),
        immediate_actions=immediate,
        total_violations=len(violations),
    )
